const canvas = document.getElementById('chartCanvas');
const context = canvas.getContext('2d');
const pointCount = document.getElementById('pointCount');
const sampleCount = document.getElementById('sampleCount');
const inputHead = document.getElementById('inputHead');
const inputBody = document.getElementById('inputBody');
const resultHead = document.getElementById('resultHead');
const resultBody = document.getElementById('resultBody');
const dataCount = document.getElementById('dataCount');
const chartStatus = document.getElementById('chartStatus');
const infoDialog = document.getElementById('infoDialog');
const chartLegend = document.getElementById('chartLegend');
const legendTitle = document.getElementById('legendTitle');
const regressionButton = document.getElementById('regressionButton');
const fitRate = document.getElementById('fitRate');
let regressionEnabled = false;
const datasetName = document.getElementById('datasetName');
const sampleData = { name: '反比例の測定', x: [0.8, 1.6, 2.7, 4.2], y: [[6.0, 4.4, 5.3, 7.1], [3.5, 2.7, 3.2, 2.3], [2.0, 1.6, 2.3, 1.8], [1.5, 0.9, 1.2, 1.0]] };

function clampCount(input) { const count = Math.min(12, Math.max(1, Number.parseInt(input.value, 10) || 1)); input.value = count; return count; }
function makeInput(label, value, className) { const input = document.createElement('input'); input.className = `data-input ${className}`; input.type = 'number'; input.step = 'any'; input.inputMode = 'decimal'; input.value = value ?? ''; input.setAttribute('aria-label', label); input.addEventListener('input', update); return input; }
function readGridValues() { const xInputs = [...document.querySelectorAll('.x-value')]; const yInputs = [...document.querySelectorAll('.y-value')]; const columns = xInputs.length; const measurements = columns > 0 ? yInputs.length / columns : 0; if (columns === 0) return null; return { name: datasetName.value, x: xInputs.map((input) => input.value), y: Array.from({ length: columns }, (_, column) => Array.from({ length: measurements }, (_, row) => yInputs[row * columns + column]?.value ?? '')) }; }
function renderInputs(values = readGridValues()) { const columns = clampCount(pointCount); const measurements = clampCount(sampleCount); const source = values ?? sampleData; datasetName.value = source.name ?? ''; pointCount.dataset.previousValue = columns; sampleCount.dataset.previousValue = measurements; inputHead.innerHTML = `<tr><th scope="col">項目</th>${Array.from({ length: columns }, (_, index) => `<th scope="col">データ ${index + 1}</th>`).join('')}</tr>`; inputBody.replaceChildren(); const xRow = document.createElement('tr'); xRow.innerHTML = '<th scope="row">横軸 x</th>'; for (let column = 0; column < columns; column += 1) { const cell = document.createElement('td'); cell.appendChild(makeInput(`データ ${column + 1} の x`, source.x[column] ?? '', 'x-value')); xRow.appendChild(cell); } inputBody.appendChild(xRow); for (let rowIndex = 0; rowIndex < measurements; rowIndex += 1) { const row = document.createElement('tr'); row.innerHTML = `<th scope="row">測定 ${rowIndex + 1}</th>`; for (let column = 0; column < columns; column += 1) { const cell = document.createElement('td'); cell.appendChild(makeInput(`データ ${column + 1} の測定 ${rowIndex + 1}`, source.y[column]?.[rowIndex] ?? '', 'y-value')); row.appendChild(cell); } inputBody.appendChild(row); } dataCount.textContent = `${columns} 列`; update(); }
function readNumber(input) { const value = Number.parseFloat(input.value); return Number.isFinite(value) ? value : null; }
function getData() { const xInputs = [...document.querySelectorAll('.x-value')]; const yInputs = [...document.querySelectorAll('.y-value')]; const measurements = clampCount(sampleCount); const data = []; xInputs.forEach((input, column) => { const x = readNumber(input); const values = yInputs.filter((_, index) => index % xInputs.length === column).slice(0, measurements).map(readNumber).filter((value) => value !== null); if (x === null || values.length === 0) return; const mean = values.reduce((sum, value) => sum + value, 0) / values.length; const variance = values.length > 1 ? values.reduce((sum, value) => sum + (value - mean) ** 2, 0) / (values.length - 1) : 0; data.push({ x, mean, error: Math.sqrt(variance) / Math.sqrt(values.length) }); }); return data; }
function getRegression(data) { if (data.length < 2) return null; const meanX = data.reduce((sum, point) => sum + point.x, 0) / data.length; const meanY = data.reduce((sum, point) => sum + point.mean, 0) / data.length; const denominator = data.reduce((sum, point) => sum + (point.x - meanX) ** 2, 0); if (denominator === 0) return null; const slope = data.reduce((sum, point) => sum + (point.x - meanX) * (point.mean - meanY), 0) / denominator; const intercept = meanY - slope * meanX; const total = data.reduce((sum, point) => sum + (point.mean - meanY) ** 2, 0); const residual = data.reduce((sum, point) => sum + (point.mean - (slope * point.x + intercept)) ** 2, 0); return { slope, intercept, rSquared: total === 0 ? 1 : Math.max(0, 1 - residual / total) }; }
function format(value) { return Number.isInteger(value) ? String(value) : value.toFixed(3).replace(/0+$/, '').replace(/\.$/, ''); }
function getAxisExponent(maxValue) { if (maxValue >= 0.1 && maxValue < 100) return 0; if (maxValue === 0) return 0; return Math.floor(Math.log10(Math.abs(maxValue))); }
function formatAxis(value, exponent, isYAxis = false) { const scaled = value / (10 ** exponent); if (isYAxis && exponent === 0 && Math.abs(value) < 10) return scaled.toFixed(1); return scaled.toFixed(1).replace(/\.0$/, ''); }
function niceAxisLimit(value) { if (value < 10) return Math.max(5, Math.ceil(value / 5) * 5); if (value < 100) return Math.ceil(value / 20) * 20; const exponent = 10 ** Math.floor(Math.log10(value)); return Math.ceil(value / exponent) * exponent; }
function getSparseCorner(data) { if (data.length === 0) return 'corner-top-right'; const positiveX = data.filter((point) => point.x >= 0).map((point) => point.x); const positiveY = data.filter((point) => point.mean >= 0).map((point) => point.mean); const maxX = Math.max(1, ...positiveX); const maxY = Math.max(1, ...positiveY); const rightTopOccupied = data.some((point) => point.x >= maxX * 0.65 && point.mean >= maxY * 0.65); if (!rightTopOccupied) return 'corner-top-right'; const counts = { 'corner-top-right': 0, 'corner-top-left': 0, 'corner-bottom-left': 0, 'corner-bottom-right': 0 }; data.forEach((point) => { if (point.x >= 0 && point.mean >= 0) counts['corner-top-right'] += 1; if (point.x < 0 && point.mean >= 0) counts['corner-top-left'] += 1; if (point.x < 0 && point.mean < 0) counts['corner-bottom-left'] += 1; if (point.x >= 0 && point.mean < 0) counts['corner-bottom-right'] += 1; }); return Object.keys(counts).sort((a, b) => counts[a] - counts[b])[0]; }
function renderResults(data) { resultHead.innerHTML = `<tr><th scope="col">項目</th>${data.map((_, index) => `<th scope="col">データ ${index + 1}</th>`).join('')}</tr>`; resultBody.replaceChildren(); legendTitle.textContent = datasetName.value.trim() || 'データセット'; chartLegend.className = `chart-legend ${getSparseCorner(data)}`; if (data.length === 0) { resultBody.innerHTML = '<tr><td colspan="2">数値を入力してください</td></tr>'; return; } const rows = [{ label: '横軸 x', value: (point) => format(point.x) }, { label: '平均 y', value: (point) => format(point.mean) }, { label: '標準誤差', value: (point) => format(point.error) }]; rows.forEach((rowData) => { const row = document.createElement('tr'); const labelCell = document.createElement('th'); labelCell.scope = 'row'; labelCell.textContent = rowData.label; if (rowData.label === '標準誤差') { const button = document.createElement('button'); button.className = 'info-button'; button.type = 'button'; button.textContent = 'i'; button.setAttribute('aria-label', '標準誤差の説明'); button.addEventListener('click', () => infoDialog.showModal()); labelCell.appendChild(button); } row.appendChild(labelCell); data.forEach((point) => { const cell = document.createElement('td'); cell.textContent = rowData.value(point); row.appendChild(cell); }); resultBody.appendChild(row); }); }
function moveVerticalInput(input, direction) { const cell = input.closest('td'); const row = input.closest('tr'); if (!cell || !row) return; const targetRow = direction < 0 ? row.previousElementSibling : row.nextElementSibling; const target = targetRow?.querySelector(`td:nth-child(${cell.cellIndex + 1}) input`); if (target) { target.focus(); target.select(); } }
function pasteTableValues(event) { const target = event.target.closest('input'); if (!target || !target.classList.contains('data-input')) return; const text = event.clipboardData?.getData('text/plain') || ''; if (!text.includes('\t') && !text.includes('\n')) return; const sourceRows = text.replace(/\r/g, '').split('\n').filter((row) => row.length > 0).map((row) => row.split('\t')); const startCell = target.closest('td'); const startRow = target.closest('tr'); if (!startCell || !startRow) return; event.preventDefault(); const startRowIndex = [...inputBody.rows].indexOf(startRow); const startColumnIndex = startCell.cellIndex - 1; sourceRows.forEach((sourceRow, rowOffset) => { const destinationRow = inputBody.rows[startRowIndex + rowOffset]; if (!destinationRow) return; sourceRow.forEach((value, columnOffset) => { const destinationCell = destinationRow.cells[startColumnIndex + columnOffset + 1]; const destinationInput = destinationCell?.querySelector('input'); if (destinationInput && value.trim() !== '') destinationInput.value = value.trim(); }); }); update(); }
function getQuadrantStatus(data) { const quadrants = new Set(); data.forEach((point) => { if (point.x >= 0 && point.mean >= 0) quadrants.add('第1象限'); if (point.x < 0 && point.mean >= 0) quadrants.add('第2象限'); if (point.x < 0 && point.mean < 0) quadrants.add('第3象限'); if (point.x >= 0 && point.mean < 0) quadrants.add('第4象限'); }); return quadrants.size > 0 ? [...quadrants].join('・') : 'データなし'; }
function draw(data, size = canvas.clientWidth) { context.clearRect(0, 0, size, size); context.fillStyle = '#fcfdfd'; context.fillRect(0, 0, size, size); const xValues = data.map((point) => point.x); const yValues = data.flatMap((point) => [point.mean + point.error, point.mean - point.error]); const hasNegativeX = xValues.some((value) => value < 0); const hasNegativeY = yValues.some((value) => value < 0); const xPositiveMax = Math.max(1, ...xValues.filter((value) => value >= 0)); const xNegativeMax = Math.max(1, ...xValues.filter((value) => value < 0).map((value) => Math.abs(value))); const yPositiveMax = Math.max(1, ...yValues.filter((value) => value >= 0)); const yNegativeMax = Math.max(1, ...yValues.filter((value) => value < 0).map((value) => Math.abs(value))); const xLimit = Math.max(xPositiveMax, xNegativeMax) * 1.18; const yLimit = niceAxisLimit(Math.max(yPositiveMax, yNegativeMax) * 1.18); const xMin = hasNegativeX ? -xLimit : 0; const yMin = hasNegativeY ? -yLimit : 0; const xRange = xLimit - xMin; const yRange = yLimit - yMin; const exponent = getAxisExponent(Math.max(xLimit, yLimit)); const padding = 72; const plotSize = size - padding * 2; const toX = (value) => padding + ((value - xMin) / xRange) * plotSize; const toY = (value) => size - padding - ((value - yMin) / yRange) * plotSize; chartStatus.textContent = getQuadrantStatus(data);
  context.strokeStyle = '#e7edef'; context.lineWidth = 1; const divisions = 5; for (let index = 0; index <= divisions; index += 1) { const xValue = xMin + (xRange / divisions) * index; const yValue = yMin + (yRange / divisions) * index; const px = toX(xValue); const py = toY(yValue); context.beginPath(); context.moveTo(px, padding); context.lineTo(px, size - padding); context.stroke(); context.beginPath(); context.moveTo(padding, py); context.lineTo(size - padding, py); context.stroke(); context.fillStyle = '#65747d'; context.font = '24px sans-serif'; context.fillText(formatAxis(xValue, exponent), px - 18, size - padding + 30); context.fillText(formatAxis(yValue, exponent, true), 8, py + 8); }
  if (exponent !== 0) { context.fillStyle = '#65747d'; context.font = '22px sans-serif'; context.fillText(`×10^${exponent}`, padding + 4, padding - 16); } const xAxisY = toY(0); const yAxisX = toX(0); context.strokeStyle = '#60717b'; context.fillStyle = '#60717b'; context.lineWidth = 1.5; context.beginPath(); context.moveTo(padding, xAxisY); context.lineTo(size - padding, xAxisY); context.stroke(); context.beginPath(); context.moveTo(toX(0), padding); context.lineTo(yAxisX, size - padding); context.stroke(); context.beginPath(); context.moveTo(size - padding, xAxisY); context.lineTo(size - padding - 10, xAxisY - 5); context.lineTo(size - padding - 10, xAxisY + 5); context.closePath(); context.fill(); context.beginPath(); context.moveTo(yAxisX, padding); context.lineTo(yAxisX - 5, padding + 10); context.lineTo(yAxisX + 5, padding + 10); context.closePath(); context.fill(); context.fillStyle = '#50616b'; context.font = 'italic 36px "KaTeX Math", "STIX Two Math", "Cambria Math", "Times New Roman", serif'; context.fillText('x', size - padding + 10, xAxisY + 10); context.fillText('y', yAxisX + 10, padding - 14);
  data.forEach((point) => { const px = toX(point.x); const meanY = toY(point.mean); const topY = toY(point.mean + point.error); const bottomY = toY(point.mean - point.error); context.strokeStyle = '#e56b4d'; context.lineWidth = 2; context.beginPath(); context.moveTo(px, topY); context.lineTo(px, bottomY); context.moveTo(px - 7, topY); context.lineTo(px + 7, topY); context.moveTo(px - 7, bottomY); context.lineTo(px + 7, bottomY); context.stroke(); context.fillStyle = '#e56b4d'; context.beginPath(); context.arc(px, meanY, 5, 0, Math.PI * 2); context.fill(); context.strokeStyle = '#fff'; context.lineWidth = 1.5; context.stroke(); });
  const regression = regressionEnabled ? getRegression(data) : null; if (regression) { context.strokeStyle = '#327b9f'; context.lineWidth = 2.5; context.setLineDash([8, 5]); context.beginPath(); context.moveTo(toX(xMin), toY(regression.slope * xMin + regression.intercept)); context.lineTo(toX(xLimit), toY(regression.slope * xLimit + regression.intercept)); context.stroke(); context.setLineDash([]); }
}
function resizeCanvas() { const size = canvas.clientWidth; const ratio = window.devicePixelRatio || 1; canvas.width = Math.max(1, Math.floor(size * ratio)); canvas.height = Math.max(1, Math.floor(size * ratio)); context.setTransform(ratio, 0, 0, ratio, 0, 0); draw(getData(), size); }
function update() { const data = getData(); const regression = getRegression(data); fitRate.textContent = regressionEnabled && regression ? `適合度 ${(regression.rSquared * 100).toFixed(1)}%` : ''; regressionButton.classList.toggle('active', regressionEnabled); resizeCanvas(); renderResults(data); }
function downloadChart() { const exportCanvas = document.createElement('canvas'); exportCanvas.width = canvas.width; exportCanvas.height = canvas.height; const exportContext = exportCanvas.getContext('2d'); exportContext.drawImage(canvas, 0, 0); const ratio = window.devicePixelRatio || 1; const legendWidth = 230 * ratio; const legendHeight = 76 * ratio; const margin = 16 * ratio; const legendX = exportCanvas.width - legendWidth - margin; const legendY = margin; const accent = '#e56b4d'; exportContext.fillStyle = '#ffffffeb'; exportContext.strokeStyle = '#d8e0e5'; exportContext.lineWidth = ratio; exportContext.fillRect(legendX, legendY, legendWidth, legendHeight); exportContext.strokeRect(legendX, legendY, legendWidth, legendHeight); exportContext.fillStyle = '#18232d'; exportContext.font = `700 ${20 * ratio}px sans-serif`; exportContext.fillText(datasetName.value.trim() || 'データセット', legendX + 12 * ratio, legendY + 25 * ratio); exportContext.fillStyle = accent; exportContext.beginPath(); exportContext.arc(legendX + 17 * ratio, legendY + 48 * ratio, 4 * ratio, 0, Math.PI * 2); exportContext.fill(); exportContext.strokeStyle = accent; exportContext.lineWidth = 2 * ratio; exportContext.beginPath(); exportContext.moveTo(legendX + 37 * ratio, legendY + 39 * ratio); exportContext.lineTo(legendX + 37 * ratio, legendY + 57 * ratio); exportContext.moveTo(legendX + 32 * ratio, legendY + 39 * ratio); exportContext.lineTo(legendX + 42 * ratio, legendY + 39 * ratio); exportContext.moveTo(legendX + 32 * ratio, legendY + 57 * ratio); exportContext.lineTo(legendX + 42 * ratio, legendY + 57 * ratio); exportContext.stroke(); exportContext.fillStyle = '#6b7883'; exportContext.font = `${12 * ratio}px sans-serif`; exportContext.fillText('平均値 / 標準誤差', legendX + 52 * ratio, legendY + 51 * ratio); exportCanvas.toBlob((blob) => { if (!blob) return; const link = document.createElement('a'); link.download = `${datasetName.value.trim() || 'error-bar-graph'}.png`; link.href = URL.createObjectURL(blob); link.click(); URL.revokeObjectURL(link.href); }, 'image/png'); }
function saveBlob(blob, fileName) { const link = document.createElement('a'); link.download = fileName; link.href = URL.createObjectURL(blob); link.click(); URL.revokeObjectURL(link.href); }
function downloadSvg() { const image = canvas.toDataURL('image/png'); const width = canvas.width; const height = canvas.height; const ratio = window.devicePixelRatio || 1; const boxWidth = 230 * ratio; const boxHeight = 76 * ratio; const margin = 16 * ratio; const legendClass = [...chartLegend.classList].find((name) => name.startsWith('corner-')) || 'corner-top-right'; const positions = { 'corner-top-right': [width - boxWidth - margin, margin], 'corner-top-left': [70 * ratio, margin], 'corner-bottom-left': [70 * ratio, height - boxHeight - 70 * ratio], 'corner-bottom-right': [width - boxWidth - 70 * ratio, height - boxHeight - 70 * ratio] }; const [legendX, legendY] = positions[legendClass]; const title = (datasetName.value.trim() || 'データセット').replace(/[<&>"']/g, ''); const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><title>${title}</title><image href="${image}" width="${width}" height="${height}"/><g><rect x="${legendX}" y="${legendY}" width="${boxWidth}" height="${boxHeight}" rx="5" fill="#ffffff" fill-opacity="0.92" stroke="#d8e0e5"/><text x="${legendX + 12 * ratio}" y="${legendY + 25 * ratio}" fill="#18232d" font-family="sans-serif" font-size="${20 * ratio}px" font-weight="700">${title}</text><circle cx="${legendX + 17 * ratio}" cy="${legendY + 48 * ratio}" r="${4 * ratio}" fill="#e56b4d"/><path d="M ${legendX + 37 * ratio} ${legendY + 39 * ratio} V ${legendY + 57 * ratio} M ${legendX + 32 * ratio} ${legendY + 39 * ratio} H ${legendX + 42 * ratio} M ${legendX + 32 * ratio} ${legendY + 57 * ratio} H ${legendX + 42 * ratio}" fill="none" stroke="#e56b4d" stroke-width="${2 * ratio}"/><text x="${legendX + 52 * ratio}" y="${legendY + 51 * ratio}" fill="#6b7883" font-family="sans-serif" font-size="${12 * ratio}px">平均値 / 標準誤差</text></g></svg>`; saveBlob(new Blob([svg], { type: 'image/svg+xml;charset=utf-8' }), `${datasetName.value.trim() || 'error-bar-graph'}.svg`); }
function csvEscape(value) { const text = String(value ?? ''); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
function downloadCsv() { const rows = [['データ名', datasetName.value.trim() || 'データセット'], [], ['データ番号', 'x', '平均 y', '標準誤差']]; getData().forEach((point, index) => rows.push([`データ ${index + 1}`, point.x, point.mean, point.error])); const csv = `\ufeff${rows.map((row) => row.map(csvEscape).join(',')).join('\r\n')}`; saveBlob(new Blob([csv], { type: 'text/csv;charset=utf-8' }), `${datasetName.value.trim() || 'error-bar-data'}.csv`); }
function hasEnteredData() { return datasetName.value !== '' || [...document.querySelectorAll('.data-input')].some((input) => input.value !== ''); }
function isSample() { const xInputs = [...document.querySelectorAll('.x-value')]; const yInputs = [...document.querySelectorAll('.y-value')]; const columns = xInputs.length; const measurements = columns > 0 ? yInputs.length / columns : 0; if (columns === 0 || !Number.isInteger(measurements)) return false; return datasetName.value === sampleData.name && xInputs.every((input, column) => Number(input.value) === sampleData.x[column]) && yInputs.every((input, index) => Number(input.value) === sampleData.y[index % columns]?.[Math.floor(index / columns)]); }
function clearData() { if (hasEnteredData() && !isSample() && !window.confirm('入力したデータを消去します。よろしいですか？')) return; datasetName.value = ''; document.querySelectorAll('.data-input').forEach((input) => { input.value = ''; }); update(); }
function handleCountChange(event) { if (hasEnteredData() && !isSample() && !window.confirm('入力したデータが消えます。設定を変更しますか？')) { event.target.value = event.target.dataset.previousValue; return; } renderInputs(); }
datasetName.addEventListener('input', update); regressionButton.addEventListener('click', () => { regressionEnabled = !regressionEnabled; update(); }); pointCount.addEventListener('change', handleCountChange); sampleCount.addEventListener('change', handleCountChange); inputBody.addEventListener('keydown', (event) => { if (event.key !== 'Enter') return; event.preventDefault(); moveVerticalInput(event.target, event.shiftKey ? -1 : 1); }); inputBody.addEventListener('paste', pasteTableValues); document.getElementById('clearButton').addEventListener('click', clearData); document.getElementById('resetButton').addEventListener('click', () => { if (hasEnteredData() && !isSample() && !window.confirm('入力したデータをサンプルに戻します。よろしいですか？')) return; pointCount.value = sampleData.x.length; sampleCount.value = sampleData.y[0].length; renderInputs(sampleData); }); document.getElementById('dialogClose').addEventListener('click', () => infoDialog.close()); document.getElementById('downloadButton').addEventListener('click', downloadChart); document.getElementById('svgButton').addEventListener('click', downloadSvg); document.getElementById('csvButton').addEventListener('click', downloadCsv); window.addEventListener('resize', resizeCanvas); renderInputs();